import { StyleSheet } from "react-native";
import { theme } from "../../../ui/theme";

export const styles = StyleSheet.create({
  heroSurface: {
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  heroFallback: {
    backgroundColor: theme.colors.glassFallbackMuted,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 12,
  },
  illustration: {
    width: 60,
    height: 60,
    marginVertical: -2,
  },
  identity: {
    flex: 1,
    flexDirection: "column",
    gap: 4,
  },
  greeting: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    letterSpacing: -0.2,
  },
  identityMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  roleChip: {
    backgroundColor: theme.colors.glassFallbackActive,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  roleChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    letterSpacing: 0.3,
  },
  initialsBadge: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textMuted,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  menuButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.glassFallbackMuted,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  menuSheet: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "flex-end",
    justifyContent: "flex-start",
    paddingTop: 86,
    paddingHorizontal: 16,
  },
  menuCard: {
    minWidth: 220,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    gap: 4,
  },
  menuEmail: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textMuted,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  menuItemPressed: {
    backgroundColor: theme.colors.surfaceMuted,
  },
  menuItemText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  menuItemDanger: {
    color: theme.colors.red,
  },
});
