import { StyleSheet } from "react-native";
import { theme } from "../../../ui/theme";

export const styles = StyleSheet.create({
  surface: {
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    padding: 14,
    gap: 10,
  },
  surfaceFallback: {
    backgroundColor: theme.colors.surface,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    letterSpacing: -0.2,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: "500",
    color: theme.colors.textMuted,
    lineHeight: 18,
  },
  illustration: {
    width: 64,
    height: 64,
    marginTop: -4,
    marginRight: -2,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    backgroundColor: "#fffdf6",
    color: theme.colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    minHeight: 44,
  },
  descriptionInput: {
    minHeight: 88,
    paddingTop: 11,
    textAlignVertical: "top",
  },
  roomField: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surfaceMuted,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 50,
    justifyContent: "center",
  },
  roomFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  roomFieldText: {
    flex: 1,
    gap: 2,
  },
  roomFieldPlaceholder: {
    fontSize: 14,
    color: theme.colors.textMuted,
  },
  roomFieldValue: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  roomFieldMeta: {
    fontSize: 12,
    fontWeight: "500",
    color: theme.colors.textMuted,
  },
  roomFieldChange: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  photoZone: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    borderStyle: "dashed",
    backgroundColor: "#fffdf6",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  photoZoneTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  photoZoneTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  photoZoneActions: {
    flexDirection: "row",
    gap: 8,
  },
  photoZoneAction: {
    flex: 1,
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.glassFallbackMuted,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  photoButtonText: {
    color: theme.colors.textPrimary,
    fontWeight: "600",
    fontSize: 13,
  },
  thumbRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  thumb: {
    width: 88,
    height: 88,
    borderRadius: 12,
    backgroundColor: "#ece6ce",
  },
  thumbActions: {
    flex: 1,
    gap: 8,
  },
  thumbActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.glassFallbackMuted,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  thumbActionText: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  thumbRemoveButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.redSoft,
    backgroundColor: "rgba(248, 197, 197, 0.18)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  thumbRemoveText: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.red,
  },
  primaryButton: {
    borderRadius: 12,
    backgroundColor: theme.colors.black,
    paddingVertical: 13,
    alignItems: "center",
    minHeight: 44,
    justifyContent: "center",
  },
  primaryButtonText: {
    color: theme.colors.white,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.2,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  controlPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  errorText: {
    color: theme.colors.red,
    fontSize: 13,
    fontWeight: "500",
    flex: 1,
  },
});
