import { StyleSheet } from "react-native";
import { theme } from "../../ui/theme";

export const styles = StyleSheet.create({
  detailsScreen: {
    flex: 1,
    backgroundColor: theme.colors.surface,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceMuted,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  modalCloseButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceMuted,
  },
  modalCloseButtonText: {
    color: theme.colors.red,
    fontWeight: "800",
    fontSize: 14,
  },
  detailsContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    gap: 16,
  },
  summaryCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    backgroundColor: "rgba(255, 253, 244, 0.94)",
    padding: 20,
    gap: 12,
  },
  summaryHeaderRow: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryHead: {
    flex: 1,
    gap: 4,
  },
  summaryIllustration: {
    height: 92,
    marginRight: -10,
    marginTop: -18,
    width: 92,
  },
  summaryTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  summaryLocation: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.25,
  },
  summaryStatusBadge: {
    alignSelf: "flex-start",
    marginTop: 4,
  },
  modalImage: {
    marginTop: 8,
    width: "100%",
    height: 240,
    borderRadius: 16,
    backgroundColor: "#ece6ce",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  modalImageFallback: {
    marginTop: 8,
    minHeight: 188,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    backgroundColor: "rgba(255, 248, 223, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    overflow: "hidden",
  },
  modalImageFallbackIllustration: {
    height: 124,
    width: 124,
  },
  modalImageFallbackText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  modalDescriptionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 4,
  },
  modalResolutionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 12,
  },
  modalDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: theme.colors.textSecondary,
  },
  modalSection: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  modalSkeletonHistory: {
    marginTop: 8,
    gap: 10,
  },
  modalSkeletonLine: {
    height: 16,
    borderRadius: 8,
    backgroundColor: "#efe8cd",
  },
  modalSkeletonLineShort: {
    width: "62%",
    height: 16,
    borderRadius: 8,
    backgroundColor: "#efe8cd",
  },
  timelineContainer: {
    marginTop: 8,
    paddingLeft: 4,
  },
  timelineItem: {
    flexDirection: "row",
    marginBottom: 20,
  },
  timelineLeft: {
    alignItems: "center",
    width: 24,
    marginRight: 12,
  },
  timelineDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    borderWidth: 4,
    borderColor: theme.colors.black,
    zIndex: 1,
    marginTop: 2,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: theme.colors.border,
    marginTop: 4,
    marginBottom: -24,
  },
  timelineContent: {
    flex: 1,
    gap: 4,
  },
  historyLine: {
    color: theme.colors.textPrimary,
    fontWeight: "800",
    fontSize: 15,
  },
  ticketMeta: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  historyNote: {
    backgroundColor: theme.colors.surfaceMuted,
    padding: 12,
    borderRadius: 12,
    marginTop: 4,
  },
  historyNoteHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  historyNoteLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  historyNoteText: {
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
  },
  lightboxOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "rgba(0,0,0,0.92)",
  },
  lightboxDismissArea: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  lightboxContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 36,
    zIndex: 1,
  },
  lightboxImage: {
    width: "100%",
    height: "100%",
  },
  lightboxCloseButton: {
    position: "absolute",
    right: 16,
    minHeight: 46,
    minWidth: 88,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ffffff55",
    backgroundColor: "#00000080",
    paddingHorizontal: 14,
    paddingVertical: 10,
    zIndex: 2,
  },
  lightboxCloseButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
});
