import { StyleSheet } from "react-native";
import { theme } from "../../ui/theme";

export const styles = StyleSheet.create({
  listContent: {
    gap: 12,
    paddingBottom: 24,
    paddingHorizontal: 2,
  },
  listHeader: {
    gap: 12,
  },
  heroCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    padding: 16,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  headerVisualColumn: {
    alignItems: "flex-end",
    gap: 8,
  },
  heroIllustration: {
    height: 96,
    marginBottom: 2,
    marginRight: -6,
    marginTop: -14,
    width: 96,
  },
  headerMeta: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.red,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  title: {
    fontSize: 24,
    fontWeight: "900",
    color: theme.colors.textPrimary,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: theme.colors.textSecondary,
  },
  signedInText: {
    marginTop: 2,
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  signOutButton: {
    alignSelf: "flex-start",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.glassFallbackMuted,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  signOutText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  workspaceButton: {
    alignSelf: "flex-start",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.black,
    backgroundColor: theme.colors.glassFallbackActive,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  workspaceButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textPrimary,
  },
  formCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    padding: 14,
    gap: 9,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.textPrimary,
  },
  composerHeaderRow: {
    minHeight: 86,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  composerTitleBlock: {
    flex: 1,
    gap: 4,
  },
  formHintText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  composerIllustration: {
    height: 92,
    marginRight: -8,
    marginTop: -14,
    width: 92,
  },
  input: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: "#fffdf4",
    color: theme.colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  selectorInput: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.glassFallbackMuted,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  selectorInputRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  selectorPlaceholderText: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textMuted,
  },
  selectorValueText: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textPrimary,
    fontWeight: "700",
  },
  selectorActionText: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.red,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  selectedRoomMetaRow: {
    marginTop: -2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectedRoomMetaText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: "600",
  },
  clearRoomText: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.red,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  descriptionInput: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  primaryButton: {
    borderRadius: 12,
    backgroundColor: theme.colors.black,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: theme.colors.white,
    fontWeight: "800",
    fontSize: 14,
  },
  secondaryButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.glassFallbackMuted,
    paddingVertical: 10,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: theme.colors.textPrimary,
    fontWeight: "700",
    fontSize: 14,
  },
  imageActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  imageActionButton: {
    flex: 1,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  imagePreview: {
    width: "100%",
    height: 170,
    borderRadius: 12,
    backgroundColor: "#ece6ce",
  },
  errorText: {
    color: theme.colors.red,
    fontSize: 13,
  },
  ticketCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    backgroundColor: theme.colors.surface,
    padding: 16,
    gap: 8,
  },
  ticketHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  ticketTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  ticketMeta: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ticketDescription: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  ticketCardImage: {
    marginTop: 4,
    width: "100%",
    height: 160,
    borderRadius: 16,
    backgroundColor: "#ece6ce",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.25,
  },
  emptyText: {
    marginTop: 8,
    color: theme.colors.textMuted,
    fontSize: 14,
  },
  ticketListEmptyState: {
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  emptyIllustration: {
    height: 116,
    width: 116,
  },
  emptyTitle: {
    marginTop: 2,
    color: theme.colors.textPrimary,
    fontSize: 17,
    fontWeight: "900",
  },
  footerSpace: {
    paddingVertical: 8,
  },
  roomSelectorScreen: {
    flex: 1,
    backgroundColor: theme.colors.surface,
  },
  androidSheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  androidSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.32)",
  },
  androidSheetCard: {
    maxHeight: "92%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
  },
  roomSelectorHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceMuted,
  },
  roomSelectorContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 14,
    gap: 9,
  },
  filterLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingBottom: 2,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.glassFallbackMuted,
    minHeight: 42,
    minWidth: 56,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  filterChipWide: {
    minWidth: 104,
  },
  filterChipActive: {
    borderColor: theme.colors.black,
    backgroundColor: theme.colors.glassFallbackActive,
  },
  filterChipText: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  filterChipTextActive: {
    fontWeight: "800",
  },
  selectorResultsText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: "600",
    marginTop: 2,
  },
  roomList: {
    paddingTop: 4,
    paddingBottom: 28,
    gap: 8,
  },
  roomListItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: "#fffdf4",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  roomListItemActive: {
    borderColor: theme.colors.black,
    backgroundColor: "#fff2b8",
  },
  roomCodeText: {
    fontSize: 15,
    fontWeight: "900",
    color: theme.colors.textPrimary,
  },
  roomMetaText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: "600",
  },
  detailsScreen: {
    flex: 1,
    backgroundColor: theme.colors.surface,
  },
  detailsContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    gap: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceMuted,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  modalCloseButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.glassFallbackMuted,
  },
  controlPressed: {
    transform: [{ scale: 0.98 }],
  },
  controlDisabled: {
    borderColor: "rgba(111, 103, 91, 0.28)",
    backgroundColor: "rgba(255, 255, 255, 0.48)",
  },
  modalCloseButtonText: {
    color: theme.colors.red,
    fontWeight: "800",
    fontSize: 14,
  },
  summaryCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    backgroundColor: "#fffdf4",
    padding: 20,
    gap: 12,
  },
  summaryHead: {
    gap: 4,
  },
  summaryTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  summaryLocation: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  summaryStatusBadge: {
    alignSelf: "flex-start",
    marginTop: 4,
  },
  modalDescriptionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 4,
  },
  modalResolutionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 12,
  },
  modalDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: theme.colors.textSecondary,
  },
  modalSkeletonBlock: {
    marginTop: 8,
    height: 52,
    borderRadius: 10,
    backgroundColor: "#efe8cd",
  },
  modalImage: {
    marginTop: 8,
    width: "100%",
    height: 240,
    borderRadius: 16,
    backgroundColor: "#ece6ce",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  modalSection: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    letterSpacing: -0.5,
  },
  modalSkeletonHistory: {
    marginTop: 8,
    gap: 10,
  },
  modalSkeletonLine: {
    height: 16,
    borderRadius: 8,
    backgroundColor: "#efe8cd",
  },
  modalSkeletonLineShort: {
    width: "62%",
    height: 16,
    borderRadius: 8,
    backgroundColor: "#efe8cd",
  },
  timelineContainer: {
    marginTop: 8,
    paddingLeft: 4,
  },
  timelineItem: {
    flexDirection: "row",
    marginBottom: 20,
  },
  timelineLeft: {
    alignItems: "center",
    width: 24,
    marginRight: 12,
  },
  timelineDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    borderWidth: 4,
    borderColor: theme.colors.black,
    zIndex: 1,
    marginTop: 2,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: theme.colors.border,
    marginTop: 4,
    marginBottom: -24,
  },
  timelineContent: {
    flex: 1,
    gap: 4,
  },
  historyLine: {
    color: theme.colors.textPrimary,
    fontWeight: "800",
    fontSize: 15,
  },
  historyNote: {
    backgroundColor: theme.colors.surfaceMuted,
    padding: 12,
    borderRadius: 12,
    marginTop: 4,
  },
  historyNoteLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  historyNoteHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  historyNoteText: {
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
  },
});
